FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=stronghands/stronghands
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY stronghands.tar.gz /stronghands.tar.gz
RUN tar -xvf /stronghands.tar.gz

#ADD . /stronghands
RUN cd /stronghands/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /stronghands && scripts/windows-crosscompile/compile-stronghands.sh
